### PR TITLE
Iss6

### LINKED ISSUE #6: create_database-models
# REQUIREMENTS
Create the project database and the needed models, based on the database design.

# DESIGN
checker-db

# Acceptance Criteria
List all required acceptance criteria
- [ ] Comply with the design diagram
- [ ] Comply the basic queries tests
- [ ] Create users models
- [ ] Create checks models

### LINKED ISSUE #7: Checker Interface mockup coding
# REQUIREMENTS
Code the checker interface.

# DESIGN
Desktop - 1
Google Pixel 2 XL - 1

# Acceptance Criteria
List all required acceptance criteria
- [ ] The interface have to respect the design.
- [ ] The interfaces have to be usefull

### LINKED ISSUE #8: Checker module development
# REQUIREMENTS
Development of the Check module.

# DESIGN
Desktop - 1
Google Pixel 2 XL - 1

# Acceptance Criteria
List all required acceptance criteria
- [ ] The user can introduce his private_number
- [ ] The user can check in / out.
- [ ] The user get feedback about his checking.

### PR DESCRIPTION
**Pull request by LPMendoza**
# Checker module where the employees can check in and check out.
 
## Module where the employees can check in and check out typing their private number:
* The user can type its private number.
* The system check in the first time and the second time the systema will check out.
* If the user already have checked the systema will notice it.
* If the private number doesn't exist the system will notificate it.

## Testing: Help me how can I test or look at the changes?
After download the project, you will have to setup the database configuration:
* In the file /config/database.yml you have to type the credential of you database.
* Then type in the terminal the next command: **rails db:create db:migrate**
* This command will create the database and tables of the project.
* Then to see the checker module go to the rout **/checks**
* The you have to create a company and a user because the admin is not ready. So enter to de rails console with the command: **rails console**
* Type the next commands:
```
Company.create!({name: 'Coca Cola', address: 'USA'})
User.create!({email: 'Israel', position: 'Programmer', enabled:
 1, private_number: 123, company_id: 1})
```
* These commands will create and user that belongs to the company Coca Cola. The private number of this employee is: 123
* Now you can use this private number to test the Checker module.
image
image

### CODE REVIEW

**Comment by n0b0dy-su** [comment]
please, add tmp/ to the .gitignore

**Comment by jnegrete15** [comment]
great progress!

**Review by jnegrete15 — APPROVED** [review]

**Review by OchoaHub — APPROVED** [review]
Nice, i guess

**Review by n0b0dy-su — APPROVED** [review]
it's ok

**Review by jnegrete15 — APPROVED** [review]

**Review by glorianayeli — APPROVED** [review]
You can add  Arial danmarks  in html.

**Comment by n0b0dy-su** [comment]
issg approved

**Pull request merged**
